apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: main-igw
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-1
    vpcIdSelector:
      matchLabels:
        app: main-vpc
    tags:
      Name: main-igw
      ManagedBy: crossplane
  providerConfigRef:
    name: main
    kind: ProviderConfig