apiVersion: organizations.aws.m.upbound.io/v1beta1
kind: Organization
metadata:
  name: mathod.io
  namespace: crossplane-system
spec:
  forProvider:
    featureSet: ALL
  providerConfigRef:
    name: main
    kind: ProviderConfig
