apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-main
  namespace: crossplane-system
  labels:
    app: vpc-main
spec:
  forProvider:
    region: eu-west-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      Name: vpc-main
      ManagedBy: crossplane
  providerConfigRef:
    name: main
    kind: ProviderConfig